@startuml delete_song
actor User as User
participant View as View
participant "MyViewModel" as VM
participant "CoroutineScope" as Scope

User -> View: Click on IconButton
activate View
View --> VM: Call deleteSong(items)
activate VM
VM -> Scope: Launch coroutine
activate Scope
Scope --> VM: Call deleteSong(items)
activate VM
VM --> VM: Delete song from database
VM --> View: Update songflow
deactivate VM
deactivate Scope
deactivate View
@enduml
