@startuml export_song
actor User
participant View
participant "MyViewModel" as VM
participant "SongDao" as Dao
participant "SongDataBase" as DB

User -> View: Clicks share button
activate View
View -> VM: exportSongURLtoFile(context, filename)
activate VM
VM -> Dao: getSongURL()
activate Dao
Dao -> DB: SELECT Song_url FROM MyPlayList
activate DB
DB --> Dao: Song URLs
deactivate DB
Dao --> VM: Song URLs
deactivate Dao
VM -> View: File exported
deactivate VM
View --> User: File exported
deactivate View
@enduml
